version: 0.0                                             ##使用此版本就可以
os: linux                                                ##执行动作的平台

files:
  - source: /                                            ##  / 指的是将代码中的所有文件都传送到实例上
    destination: /home/ec2-user               ##代码文件将在实例上存放的位置
permissions:
  - object: /home/ec2-user   
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - directory
      
  - object: /home/ec2-user   
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 700
    type:
      - file

hooks:
                                           
  ApplicationStart:                                        ##启动应用程序的动作
    - location: deploy.sh                   ##执行动作的脚本   
      timeout: 1000                         
      

  
      
